### PR TITLE
Bump angular-ui-router dependecy to latest available

### PR DESCRIPTION
**Pull request by diimpp**
It was hardcoded to 0.2.11 in latest release. Any reason behind it or just mistype?

### CODE REVIEW

**Comment by oscar-b** [comment]
+1, this is holding back https://github.com/angular-ui/ui-router/issues/582 for us :)

**Comment by Narzerus** [comment]
Whoops, thanks!

**Comment by Narzerus** [comment]
This PR should target development

**Comment by diimpp** [comment]
@Narzerus sure, #47 
Thanks.

**Pull request closed without merging**
