### PR TITLE
Fix wrong comma in example code.

### PR DESCRIPTION
**Pull request by jak4**

### CODE REVIEW

**Comment by Narzerus** [comment]
@jak4 Thanks for the PR, there are 2 reasons I cannot yet merge this:

1.- The PR must be done to the `development` branch not to the `master`
2.- This PR includes code about some directive, a PR should only simplement one feature at the time. Please create a PR only about the comma error (thanks about that btw didn't notice it at all)

**Comment by jak4** [comment]
Oh, my bad. I thought once the pull request is created I can push to the same branch without polluting the pull request.

Since we are already writing, are you going to implement some permission based system for showing/hiding UI elements? I hacked a very primitiv directive together which works for me, but maybe you have something fancy up your sleeve?

Best regards
  jak4

**Comment by Narzerus** [comment]
There's a discussion about it at #28 also there's a PR #37 which I will review some time this week and see if it fits Permission or if it needs further discussion. Please have a look and tell us your thoughts on it, the more heads the better.

**Comment by jak4** [comment]
I'll comment tomorrow on #28, since this is what I need as well.

Best regards
  jak4

**Pull request closed without merging**
