### PR TITLE
Define all your roles with one function call

### PR DESCRIPTION
**Pull request by chaaya**
When you have the same validation function for multiple roles you have to write a lot of the same code snippets in the defineRole function. 

Also I want my roles to defined automatically with data from the backend. I dont want to strongly type these. So i defined a new function called defineMany that takes a array of roles and in the validation callback injects the role name like this.

```javascript
Permission.defineMany(roles, function (stateParams, roleName) {
        return User.hasRole(roleName);
});
```

### CODE REVIEW

**Comment by Narzerus** [comment]
Alright, I think this makes sense for some use cases. Could you please change the name of the method to `defineManyRoles` for consistency?

Also, a couple of tests here would be great :)

**Comment by chaaya** [comment]
I will look into that tomorrow! :)

**Comment by chaaya** [comment]
@Narzerus I have now commited the new version with the renaming of the function name. Im not that familiar with writing tests but I looked at your test methods for defineRole and implemented a similair test for defineManyRoles. I did this yesterday but the commit with the message "implemented test" is incorrect.

The test was implemented in "New function to define multiple roles	7076d48" commit.

**Comment by Narzerus** [comment]
@chaaya Thanks, sorry for the delay I've been kinda busy, I'll merge this today

**Comment by Narzerus** [comment]
@chaaya one minor detail that I'm missing before merging this is that you have some tests in the `#defineRole` set which belong to the `#defineManyRoles` set.

If you can't make the changes for some reason I can do it myself, though I'll take longer as I need to make some extra time for it.


Thanks for the contribution btw!

**Comment by chaaya** [comment]
@Narzerus I will fix that tomorrow. 

Glad that I could contribute :)  I will be using it in a large app and found it neat to define many roles!

**Comment by chaaya** [comment]
@Narzerus I moved the test that was defined in the defineRoles set to a seperate one. Implemented as the snippet below.

``` javascript
describe('PermissionProvider', function () {
  describe('#defineRole (provider version)', function () {
  });
  
  describe('#defineManyRoles (provider version)', function () {
  });
});
```

**Comment by Narzerus** [comment]
Merged, creating new release, thanks for the contrib! @chaaya

**Pull request merged**
