### PR TITLE
Added a directive

### PR DESCRIPTION
**Pull request by mark-veenstra**
- Added a directive to show/hide HTML elements based on the configuration on that element
- Changed Gruntfile.js to include *.dtv.js files
- Changed documentation for the directives

I haven't changed a module / provider before. This is my first. I do not know how the tests files work that are also included in the source directory. If some of the code can be done better, please change it.
Hope it helps!

### CODE REVIEW

**Comment by Narzerus** [comment]
Mark, thanks for this PR I'll give it a good read this week. 

Two small details in your code:
1.- Please use two-space indentation only
2.- Please avoid declaring functions as comma separated.

What I mean in (2):

```javascript
// Do not do this:
var a = function () {
   // ...
}, b = function () {
  // ...
}

// Instead simply do
var a = function () {
  // ...
}
var b = function () {
  // ...
}
```

The second option is far more readable when it comes to functions as they can grow bing and you kinda get your indentation lost the other way.


Thanks for your contribution I'll make sure to do a deeper review.

Cheers!

**Comment by jak4** [comment]
I have had a look at the code, and the one thing that bugs me is: permission="CanEditUser, Admin".
So, I have permission setup to check if the Admin user can see the page, and on the page I again check if the Admin user is allowed to see GUI-Elements.

Wouldn't it be easier to leave the User-Role in the ui-router definition and use something like this "client:create" instead? Thus if the user has the permission to create a client the GUI-Element will be visible?

**Comment by jak4** [comment]
On further inspection this directive will only work with permissions/roles defined on the client-side. If the permissions/role get fetched from the server this will not work.

**Comment by Narzerus** [comment]
I think this feature request itself needs much more discussion before implementing it. 

Lets take this discussion to #40 I'll reference this PR so people can have a look aswel though I will not merge this as I think this idea hasn't reached its prime

**Pull request closed without merging**
