### PR TITLE
Store and Pass reload option while transiting from permission service

### PR DESCRIPTION
**Pull request by pratik14**
https://github.com/Narzerus/angular-permission/issues/78   Pass reload option while transiting to new state.

### CODE REVIEW

**Comment by Narzerus** [comment]
Thanks for this PR, have you tried this somewhere to see if it works?

Some details:

-1 This requires a specific ui-router version (we should specify this requirement in the bower.json file)
-2 Why not pass the whole options object and simple change the notify option?

```javascript
var transitionOptions = options;
transitionOptions.notify = false;

// ... Some code 

$state.go(toState.name, toParams, transitionOptions).then(function() {
```

**Comment by pratik14** [comment]
Yes, I have tested in my project.

1. This change of ui-router is not yet released (Latest version of ui-router is 0.2.15). But change is available on 'master' branch
2. Rest of the option are set by default in ui-router, so no need to pass them as parameter. It makes code more readable, otherwise user has to again check what options are getting passed.

**Comment by Narzerus** [comment]
1 .- We should wait for a new release to be fixed before merging this (we cannot release a version which depends on a commit instead of a full release
2 .- I defer. If I remember correctly, the options parameter passed in `$stateChangeStart` contains the options that were passed by the user, meaning that if we don't pass them to the re-emitted event we would lose them.

I'll be checking from time to time, but if ui-router's new release is out let me know so we can speed things up ;)!

**Comment by Narzerus** [comment]
We are still waiting on `ui-router`'s milestone to merge this into a release

[Milestone 0.2.16](https://github.com/angular-ui/ui-router/milestones/0.2.16)

**Pull request closed without merging**
