### PR TITLE
Permission directive

### PR DESCRIPTION
**Pull request by masterspambot**
Created permission-only and permission-except directives based proposals from #40

### CODE REVIEW

**Comment by Narzerus** [comment]
@masterspambot Great, please use only 2-space indentation though!

**Comment by emilenriquez** [comment]
hmm is there a guide on how I can use the directive on the view? @masterspambot

**Comment by emilenriquez** [comment]
<a ui-sref="auth" permission-only="anonymous">{{showLoginLink}}</a></li>
I'm doing this and I cant get it to work

**Comment by ktersius** [comment]
Using https://www.npmjs.com/package/angular-permission and the latest version 1.1.1 does not have these directives included.

**Comment by Narzerus** [comment]
Woops! Looking at all this stuff today

**Pull request merged**
